# Generated by Django 5.2 on 2025-05-06 09:51

import django.utils.timezone
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=myapp.models.generate_package_code, editable=False, max_length=8, unique=True)),
                ('type', models.CharField(choices=[('package', 'Package'), ('document', 'Document')], default='package', max_length=10)),
                ('description', models.TextField()),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picked', 'Picked')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dropped_by', models.CharField(max_length=100)),
                ('dropper_phone', models.CharField(max_length=20)),
                ('picked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('picker_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
