# Generated by Django 5.2 on 2025-05-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='shelf',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
    ]
