# Generated by Django 5.2 on 2025-05-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_package_shelf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('package', 'Package'), ('document', 'Document'), ('key', 'key')], default='package', max_length=10),
        ),
    ]
