# Generated by Django 5.2 on 2025-05-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('package', 'Package'), ('document', 'Document'), ('keys', 'keys')], default='package', max_length=10),
        ),
    ]
