# Generated by Django 5.2 on 2025-05-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_package_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='picker_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
